import { AudiomorphicPresetRecord } from './starseedDb';

export const DEFAULT_PRESETS: AudiomorphicPresetRecord[] = [
  // =========================================================================
  // --- ✨ AUDIOMORPHIC ESSENTIALS (AJUSTES AUTOMÁTICOS BASE) ---
  // =========================================================================
  {
    id: 'essential_rhythmic',
    title: 'Ritmos Musicales (Audiomorphic Essentials)',
    description: 'Alineación reactiva a transitorios, bombos y cambios tonales rítmicos en tiempo real con geometría de flor de la vida y cimática.',
    category: 'essentials',
    author: { name: 'Audiomorphic Core', handle: '@audiomorphic' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 0,
    folderPath: 'Librería/Audiomorphic Essentials',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
    params: {
      autoPilot: true,
      autoPilotMode: 'rhythmic',
      autoRandomMode: 'rhythmic',
      autoRandomOnBeat: true,
      autoRandomOnEmotionChange: true,
      autoEmotionSensitivity: 50,
      autoBeatSensitivity: 65,
      autoStyleFluidity: 55,
      autoRandomReactivitySpeed: 60,
      autoTransitionSmoothness: 70,
      autoRelationshipMode: 'technical',
      autoOffscreenFade: true,
      k: 0.992,
      psi: 2.399,
      sensitivity: 1.5,
      harmonicColor: true,
      baseHue: 200,
      hueRange: 360,
      saturation: 95,
      brightness: 12,
      sacredGeometryEnabled: true,
      sacredGeometryModes: ['flowerOfLife', 'cymatics', 'goldenSpiral'],
      sgDrawMode: 'layers',
      sgShowNodes: true,
      sgAutoResonance: true,
      sgGlobalFlowSpeed: 0.3,
      sgGlobalOpacity: 0.9,
    },
  },
  {
    id: 'essential_dj',
    title: 'Modo DJ Club (Audiomorphic Essentials)',
    description: 'Reacción percusiva agresiva con transiciones rápidas en bombos, caídas y drops de música electrónica y mezclas en vivo.',
    category: 'essentials',
    author: { name: 'Audiomorphic Core', handle: '@audiomorphic' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 1,
    folderPath: 'Librería/Audiomorphic Essentials',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
    params: {
      autoPilot: true,
      autoPilotMode: 'dj',
      autoRandomMode: 'dj',
      autoRandomOnBeat: true,
      autoRandomOnEmotionChange: true,
      autoEmotionSensitivity: 60,
      autoBeatSensitivity: 75,
      autoStyleFluidity: 60,
      autoRandomReactivitySpeed: 75,
      autoTransitionSmoothness: 80,
      autoRelationshipMode: 'rhythmic',
      autoOffscreenFade: true,
      k: 0.995,
      psi: 3.14,
      baseHue: 320,
      hueRange: 360,
      saturation: 100,
      brightness: 14,
      harmonicColor: true,
      sacredGeometryEnabled: true,
      sacredGeometryModes: ['metatron', 'torus', 'vectorEquilibrium'],
      sgDrawMode: 'layers',
      sgShowNodes: true,
      sgAutoResonance: true,
      sgGlobalFlowSpeed: 0.4,
      sgGlobalOpacity: 0.95,
    },
  },
  {
    id: 'essential_sacred',
    title: 'Resonancias Sagradas (Audiomorphic Essentials)',
    description: 'Evolución suave y contemplativa con geometrías de Metatrón, Merkaba y Sri Yantra sensibles a armónicos y frecuencias.',
    category: 'essentials',
    author: { name: 'Audiomorphic Core', handle: '@audiomorphic' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 2,
    folderPath: 'Librería/Audiomorphic Essentials',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
    params: {
      autoPilot: true,
      autoPilotMode: 'sacred',
      autoRandomMode: 'sacred',
      autoRandomOnBeat: false,
      autoRandomOnEmotionChange: true,
      autoEmotionSensitivity: 50,
      autoBeatSensitivity: 50,
      autoStyleFluidity: 70,
      autoRelationshipMode: 'empathetic',
      autoOffscreenFade: true,
      k: 1.002,
      psi: 2.399,
      baseHue: 45,
      hueRange: 300,
      saturation: 90,
      brightness: 11,
      harmonicColor: true,
      sacredGeometryEnabled: true,
      sacredGeometryModes: ['metatron', 'flowerOfLife', 'sriYantra', 'merkaba'],
      sgDrawMode: 'layers',
      sgShowNodes: true,
      sgAutoResonance: true,
      sgGlobalFlowSpeed: 0.25,
      sgGlobalOpacity: 0.9,
    },
  },
  {
    id: 'essential_rainbow',
    title: 'Sinfonía Arcoíris (Audiomorphic Essentials)',
    description: 'Espectro cromático continuo de 360 grados que modula el tono base en cada frase musical y compás melódico.',
    category: 'essentials',
    author: { name: 'Audiomorphic Core', handle: '@audiomorphic' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 3,
    folderPath: 'Librería/Audiomorphic Essentials',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
    params: {
      autoPilot: true,
      autoPilotMode: 'rainbow',
      autoRandomMode: 'rainbow',
      autoRandomOnBeat: true,
      autoRandomOnEmotionChange: true,
      autoEmotionSensitivity: 55,
      autoBeatSensitivity: 60,
      baseHue: 180,
      hueRange: 360,
      saturation: 100,
      brightness: 13,
      harmonicColor: true,
      sacredGeometryEnabled: true,
      sacredGeometryModes: ['cymatics', 'torus', 'mandala1'],
      sgDrawMode: 'layers',
      sgShowNodes: true,
      sgAutoResonance: true,
      sgGlobalFlowSpeed: 0.35,
      sgGlobalOpacity: 0.9,
    },
  },
  {
    id: 'essential_astral',
    title: 'Astromorphociberpsicodélico (Audiomorphic Essentials)',
    description: 'Fluctuación cuántica hiperdimensional y fractal holográfico con alta fluidez de estilo y variaciones de fase.',
    category: 'essentials',
    author: { name: 'Audiomorphic Core', handle: '@audiomorphic' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 4,
    folderPath: 'Librería/Audiomorphic Essentials',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
    params: {
      autoPilot: true,
      autoPilotMode: 'astral',
      autoRandomMode: 'astral',
      autoRandomOnBeat: true,
      autoRandomOnEmotionChange: true,
      autoStyleFluidity: 85,
      autoRandomReactivitySpeed: 70,
      k: 0.998,
      psi: 1.57,
      baseHue: 270,
      hueRange: 360,
      saturation: 100,
      brightness: 14,
      harmonicColor: true,
      sacredGeometryEnabled: true,
      sacredGeometryModes: ['quantumWave', 'holographicFractal', 'chakras'],
      sgDrawMode: 'layers',
      sgShowNodes: true,
      sgAutoResonance: true,
      sgGlobalFlowSpeed: 0.45,
      sgGlobalOpacity: 0.95,
    },
  },
  {
    id: 'essential_smart',
    title: 'Modo Inteligente Empático (Audiomorphic Essentials)',
    description: 'Equilibrio inteligente adaptativo que detecta la emoción de la música y sintoniza velocidad, color y geometría de forma automática.',
    category: 'essentials',
    author: { name: 'Audiomorphic Core', handle: '@audiomorphic' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 5,
    folderPath: 'Librería/Audiomorphic Essentials',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
    params: {
      autoPilot: true,
      autoPilotMode: 'smart',
      autoRandomMode: 'smart',
      autoRandomOnBeat: true,
      autoRandomOnEmotionChange: true,
      autoEmotionSensitivity: 50,
      autoBeatSensitivity: 50,
      autoStyleFluidity: 50,
      autoRelationshipMode: 'empathetic',
      k: 0.994,
      psi: 2.399,
      baseHue: 160,
      hueRange: 300,
      saturation: 90,
      brightness: 12,
      harmonicColor: true,
      sacredGeometryEnabled: true,
      sacredGeometryModes: ['flowerOfLife', 'goldenSpiral'],
      sgDrawMode: 'layers',
      sgShowNodes: true,
      sgAutoResonance: true,
    },
  },
  {
    id: 'essential_random',
    title: 'Aleatorio Total & Exploratorio (Audiomorphic Essentials)',
    description: 'Exploración impredecible y continua de parámetros visuales cada 10 segundos, descubriendo configuraciones cinemáticas únicas.',
    category: 'essentials',
    author: { name: 'Audiomorphic Core', handle: '@audiomorphic' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 6,
    folderPath: 'Librería/Audiomorphic Essentials',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
    params: {
      autoPilot: true,
      autoPilotMode: 'random',
      autoRandomMode: 'random',
      autoRandomInterval: 10,
      autoRandomOnBeat: false,
      autoRandomOnEmotionChange: false,
      k: 1.001,
      psi: 2.1,
      baseHue: 0,
      hueRange: 360,
      saturation: 95,
      brightness: 13,
      harmonicColor: true,
      sacredGeometryEnabled: true,
      sacredGeometryModes: ['metatron', 'torus'],
    },
  },

  // =========================================================================
  // --- GÉNESIS SAGRADO ---
  // =========================================================================
  {
    id: 'genesis-metatron-supremo',
    title: 'Cubo de Metatrón Supremo',
    description: 'Geometría sagrada en máxima complejidad (V:13, E:78) con capas resonantes infinitas y respiración armónica expansiva.',
    category: 'genesis',
    author: { name: 'StarSeed Core', handle: '@starseed' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 7,
    folderPath: 'Librería/Presets Oficiales/Génesis Sagrado',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
    params: {
      k: 1.006,
      psi: 2.399,
      autoPilot: true,
      autoPilotMode: 'genesis',
      genesisStage: 6,
      autoViscosity: 0.965,
      autoSpeed: 1.0,
      baseHue: 45,
      hueRange: 360,
      saturation: 100,
      brightness: 12,
      harmonicColor: true,
      sacredGeometryEnabled: true,
      sacredGeometryModes: ['metatron', 'goldenSpiral', 'flowerOfLife', 'quantumWave', 'torus'],
      sgDrawMode: 'layers',
      sgShowNodes: true,
      sgAutoResonance: true,
      sgGlobalFlowSpeed: 0.3,
      sgGlobalOpacity: 0.9,
      sgGlobalAudioReactivity: 6.0,
      autoRandomOnBeat: true,
      autoRandomMode: 'rhythmic',
    },
  },
  {
    id: 'genesis-flor-vida',
    title: 'Flor de la Vida Luminosa',
    description: 'Resonancia pura de 19 vértices y 36 aristas en régimen primario de balance yin-yang y respiración áurea.',
    category: 'genesis',
    author: { name: 'StarSeed Core', handle: '@starseed' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 8,
    folderPath: 'Librería/Presets Oficiales/Génesis Sagrado',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
    params: {
      k: 1.004,
      psi: 2.399,
      autoPilot: true,
      autoPilotMode: 'genesis',
      genesisStage: 4,
      autoViscosity: 0.97,
      autoSpeed: 0.8,
      baseHue: 155,
      hueRange: 300,
      saturation: 95,
      brightness: 12,
      harmonicColor: true,
      sacredGeometryEnabled: true,
      sacredGeometryModes: ['flowerOfLife'],
      sgDrawMode: 'layers',
      sgShowNodes: true,
      sgAutoResonance: true,
      sgGlobalFlowSpeed: 0.25,
      sgGlobalOpacity: 0.85,
      autoRandomOnBeat: true,
    },
  },
  {
    id: 'genesis-sri-yantra',
    title: 'Sri Yantra & Merkaba Tridimensional',
    description: 'Alineación primordial de 9 triángulos entrelazados y campo Merkaba de luz dorada y esmeralda con reactividad armónica sonora.',
    category: 'genesis',
    author: { name: 'StarSeed Labs', handle: '@starseed' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 9,
    folderPath: 'Librería/Presets Oficiales/Génesis Sagrado',
    createdAt: '2026-09-02T00:00:00Z',
    updatedAt: '2026-09-02T00:00:00Z',
    params: {
      k: 1.007,
      psi: 2.399,
      autoPilot: true,
      autoPilotMode: 'genesis',
      genesisStage: 5,
      autoViscosity: 0.96,
      autoSpeed: 0.9,
      baseHue: 48,
      hueRange: 320,
      saturation: 100,
      brightness: 13,
      harmonicColor: true,
      sacredGeometryEnabled: true,
      sacredGeometryModes: ['sriYantra', 'merkaba'],
      sgDrawMode: 'layers',
      sgShowNodes: true,
      sgAutoResonance: true,
      sgGlobalFlowSpeed: 0.35,
      sgGlobalOpacity: 0.95,
      autoRandomOnBeat: true,
    },
  },

  // =========================================================================
  // --- RESONANCIAS SAGRADAS & SOUND HEALING ---
  // =========================================================================
  {
    id: 'sacred-schumann-432',
    title: 'Sonoterapia Schumann 432Hz & Cuencos',
    description: 'Resonancia telúrica de 7.83Hz y 432Hz. Miel zen fluida con campos de chakras, Sri Yantra y cuencos tibetanos de relajación profunda.',
    category: 'sacred',
    author: { name: 'Solfeggio Harmonic Lab', handle: '@solfeggio' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 10,
    folderPath: 'Librería/Presets Oficiales/Resonancias Sagradas',
    createdAt: '2026-09-03T00:00:00Z',
    updatedAt: '2026-09-03T00:00:00Z',
    params: {
      k: 1.001,
      psi: 2.399,
      autoPilot: true,
      autoPilotMode: 'sacred',
      autoRandomMode: 'sacred',
      autoRandomOnBeat: false,
      autoRandomOnEmotionChange: true,
      autoEmotionSensitivity: 45,
      autoBeatSensitivity: 40,
      autoStyleFluidity: 80,
      autoViscosity: 0.985,
      autoSpeed: 0.5,
      autoRelationshipMode: 'empathetic',
      autoOffscreenFade: true,
      baseHue: 150,
      hueRange: 160,
      saturation: 85,
      brightness: 10,
      harmonicColor: true,
      harmonicSensitivity: 6.0,
      harmonicDepth: 180,
      sacredGeometryEnabled: true,
      sacredGeometryModes: ['sriYantra', 'chakras', 'flowerOfLife'],
      sgDrawMode: 'layers',
      sgShowNodes: true,
      sgAutoResonance: true,
      sgGlobalFlowSpeed: 0.2,
      sgGlobalOpacity: 0.88,
    },
  },
  {
    id: 'sacred-gregoriano',
    title: 'Canto Gregoriano & Polifonía Sacra',
    description: 'Reverberación de catedral con Merkaba dorado y Sri Yantra que se expanden majestuosamente con coros y tonos sostenidos.',
    category: 'sacred',
    author: { name: 'StarSeed Sacred Arts', handle: '@sacredarts' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 11,
    folderPath: 'Librería/Presets Oficiales/Resonancias Sagradas',
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
    params: {
      k: 1.003,
      psi: 2.399,
      autoPilot: true,
      autoPilotMode: 'sacred',
      autoRandomMode: 'sacred',
      autoRandomOnBeat: false,
      autoRandomOnEmotionChange: true,
      autoEmotionSensitivity: 65,
      autoBeatSensitivity: 45,
      autoStyleFluidity: 75,
      autoViscosity: 0.98,
      autoSpeed: 0.6,
      autoRelationshipMode: 'empathetic',
      baseHue: 42,
      hueRange: 90,
      saturation: 90,
      brightness: 11,
      harmonicColor: true,
      harmonicSensitivity: 7.5,
      sacredGeometryEnabled: true,
      sacredGeometryModes: ['merkaba', 'sriYantra', 'flowerOfLife'],
      sgDrawMode: 'layers',
      sgShowNodes: true,
      sgAutoResonance: true,
      sgGlobalFlowSpeed: 0.22,
      sgGlobalOpacity: 0.9,
    },
  },

  // =========================================================================
  // --- ARMÓNICOS & GÉNEROS MUSICALES ---
  // =========================================================================
  {
    id: 'harmonic-solfeggio-528',
    title: 'Frecuencia de Transformación 528Hz',
    description: 'Afinación áurea milagrosa y transiciones armónicas continuas que siguen las progresiones sonoras puras.',
    category: 'harmonic',
    author: { name: 'Omnifrecuencias Labs', handle: '@omnifrecuencias' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 12,
    folderPath: 'Librería/Presets Oficiales/Armónicos',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
    params: {
      k: 1.008,
      psi: 2.399,
      autoPilot: true,
      autoPilotMode: 'harmonic',
      rootNote: 0,
      autoViscosity: 0.96,
      autoSpeed: 1.2,
      baseHue: 120,
      hueRange: 360,
      saturation: 100,
      brightness: 11,
      harmonicColor: true,
      harmonicSensitivity: 6.5,
      harmonicDepth: 360,
      autoRandomOnBeat: true,
      autoRandomMode: 'rhythmic',
    },
  },
  {
    id: 'harmonic-circulo-quintas',
    title: 'Círculo Cósmico de Quintas',
    description: 'Mapeo modal de tonalidades cromáticas con rotación angular según el espectro armónico y cambios de acordes.',
    category: 'harmonic',
    author: { name: 'StarSeed Core', handle: '@starseed' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 13,
    folderPath: 'Librería/Presets Oficiales/Armónicos',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
    params: {
      k: 1.005,
      psi: 1.618,
      autoPilot: true,
      autoPilotMode: 'harmonic',
      rootNote: 7,
      autoViscosity: 0.955,
      autoSpeed: 1.0,
      baseHue: 280,
      hueRange: 360,
      saturation: 100,
      brightness: 10,
      harmonicColor: true,
      harmonicSensitivity: 5.0,
      harmonicDepth: 360,
      autoRandomOnBeat: true,
    },
  },
  {
    id: 'harmonic-filarmonica',
    title: 'Sinfonía Clásica & Filarmónica',
    description: 'Diseñado para orquesta sinfónica, cuerdas y pianos. Detección de dinámicas forte/pianissimo con transiciones sedosas en azul zafiro y oro.',
    category: 'harmonic',
    author: { name: 'Symphony Virtuoso', handle: '@virtuoso' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 14,
    folderPath: 'Librería/Presets Oficiales/Armónicos',
    createdAt: '2026-09-03T00:00:00Z',
    updatedAt: '2026-09-03T00:00:00Z',
    params: {
      k: 1.004,
      psi: 2.399,
      autoPilot: true,
      autoPilotMode: 'harmonic',
      autoRandomMode: 'rainbow',
      autoRandomOnBeat: true,
      autoRandomOnEmotionChange: true,
      autoEmotionSensitivity: 75,
      autoBeatSensitivity: 50,
      autoStyleFluidity: 78,
      autoRandomReactivitySpeed: 62,
      autoTransitionSmoothness: 85,
      autoRelationshipMode: 'empathetic',
      autoViscosity: 0.97,
      autoSpeed: 0.85,
      baseHue: 240,
      hueRange: 280,
      saturation: 90,
      brightness: 12,
      harmonicColor: true,
      harmonicSensitivity: 7.0,
      harmonicDepth: 300,
      sacredGeometryEnabled: true,
      sacredGeometryModes: ['goldenSpiral', 'vectorEquilibrium', 'flowerOfLife'],
      sgDrawMode: 'layers',
      sgShowNodes: true,
      sgAutoResonance: true,
      sgGlobalFlowSpeed: 0.28,
      sgGlobalOpacity: 0.9,
    },
  },
  {
    id: 'harmonic-deep-house',
    title: 'Deep House Ibiza Sunset',
    description: 'Cálido atardecer balear con tonos coral, ámbar y violeta. Pulso 4/4 orgánico, toroides envolventes y viscosidad suave.',
    category: 'harmonic',
    author: { name: 'Ibiza Soundscape', handle: '@ibizasound' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 15,
    folderPath: 'Librería/Presets Oficiales/Armónicos',
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
    params: {
      k: 1.006,
      psi: 2.399,
      autoPilot: true,
      autoPilotMode: 'rhythmic',
      autoRandomMode: 'rhythmic',
      autoRandomOnBeat: true,
      autoRandomOnEmotionChange: true,
      autoEmotionSensitivity: 58,
      autoBeatSensitivity: 68,
      autoStyleFluidity: 65,
      autoRandomReactivitySpeed: 70,
      autoTransitionSmoothness: 75,
      autoRelationshipMode: 'rhythmic',
      autoViscosity: 0.965,
      autoSpeed: 1.05,
      baseHue: 25,
      hueRange: 80,
      saturation: 100,
      brightness: 13,
      harmonicColor: true,
      sacredGeometryEnabled: true,
      sacredGeometryModes: ['torus', 'flowerOfLife', 'mandala1'],
      sgDrawMode: 'layers',
      sgShowNodes: true,
      sgAutoResonance: true,
      sgGlobalFlowSpeed: 0.32,
      sgGlobalOpacity: 0.92,
    },
  },

  // =========================================================================
  // --- RITMOS MUSICALES, CLUB & ESCENARIOS ---
  // =========================================================================
  {
    id: 'rhythm-techno-club',
    title: 'Púlsar Rítmico de Graves (Live DJ)',
    description: 'Detección aguda de transitorios y bombos con salto angular en cada beat, estallidos cromáticos neón y viscosidad ajustada.',
    category: 'rhythmic',
    author: { name: 'Nexus Club', handle: '@nexusclub' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 16,
    folderPath: 'Librería/Presets Oficiales/Ritmos Musicales',
    createdAt: '2026-09-02T00:00:00Z',
    updatedAt: '2026-09-02T00:00:00Z',
    params: {
      k: 1.010,
      psi: 2.399,
      autoPilot: true,
      autoPilotMode: 'dj',
      autoRandomMode: 'dj',
      autoRandomOnBeat: true,
      autoEmotionSensitivity: 60,
      autoBeatSensitivity: 80,
      autoStyleFluidity: 65,
      autoRandomReactivitySpeed: 80,
      autoTransitionSmoothness: 80,
      autoRelationshipMode: 'rhythmic',
      autoViscosity: 0.94,
      autoSpeed: 1.35,
      baseHue: 330,
      hueRange: 360,
      saturation: 100,
      brightness: 14,
      harmonicColor: true,
      sacredGeometryEnabled: true,
      sacredGeometryModes: ['metatron', 'torus'],
      sgDrawMode: 'layers',
      sgShowNodes: true,
      sgAutoResonance: true,
      sgGlobalFlowSpeed: 0.45,
      sgGlobalOpacity: 0.95,
    },
  },
  {
    id: 'rhythm-synthwave-80s',
    title: 'Cyber Synthwave 80s (Outrun)',
    description: 'Estética retrofuturista neón magenta y cian brillante. Reacción instantánea a redoblantes de batería electrónica y arpegios analógicos.',
    category: 'rhythmic',
    author: { name: 'RetroGrid Collective', handle: '@retrogrid' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 17,
    folderPath: 'Librería/Presets Oficiales/Ritmos Musicales',
    createdAt: '2026-09-03T00:00:00Z',
    updatedAt: '2026-09-03T00:00:00Z',
    params: {
      k: 1.009,
      psi: 2.399,
      autoPilot: true,
      autoPilotMode: 'rhythmic',
      autoRandomMode: 'rhythmic',
      autoRandomOnBeat: true,
      autoRandomOnEmotionChange: true,
      autoEmotionSensitivity: 55,
      autoBeatSensitivity: 78,
      autoStyleFluidity: 60,
      autoRandomReactivitySpeed: 75,
      autoTransitionSmoothness: 72,
      autoRelationshipMode: 'technical',
      autoViscosity: 0.95,
      autoSpeed: 1.25,
      baseHue: 310,
      hueRange: 160,
      saturation: 100,
      brightness: 14,
      harmonicColor: true,
      sacredGeometryEnabled: true,
      sacredGeometryModes: ['cymatics', 'goldenSpiral', 'vectorEquilibrium'],
      sgDrawMode: 'layers',
      sgShowNodes: true,
      sgAutoResonance: true,
      sgGlobalFlowSpeed: 0.38,
      sgGlobalOpacity: 0.95,
    },
  },
  {
    id: 'rhythm-flamenco',
    title: 'Flamenco Puro & Pasión Andaluza',
    description: 'Rojo carmesí y oro ardiente. Ataque percusivo hiper-preciso al compás de palmas, zapateado y rasgueos de guitarra flamenca.',
    category: 'rhythmic',
    author: { name: 'Duende Sonoro', handle: '@duende' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 18,
    folderPath: 'Librería/Presets Oficiales/Ritmos Musicales',
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
    params: {
      k: 1.008,
      psi: 2.399,
      autoPilot: true,
      autoPilotMode: 'rhythmic',
      autoRandomMode: 'rhythmic',
      autoRandomOnBeat: true,
      autoRandomOnEmotionChange: true,
      autoEmotionSensitivity: 70,
      autoBeatSensitivity: 85,
      autoStyleFluidity: 58,
      autoRandomReactivitySpeed: 82,
      autoTransitionSmoothness: 68,
      autoRelationshipMode: 'rhythmic',
      autoViscosity: 0.945,
      autoSpeed: 1.2,
      baseHue: 355,
      hueRange: 75,
      saturation: 100,
      brightness: 13,
      harmonicColor: true,
      sacredGeometryEnabled: true,
      sacredGeometryModes: ['flowerOfLife', 'torus', 'goldenSpiral'],
      sgDrawMode: 'layers',
      sgShowNodes: true,
      sgAutoResonance: true,
      sgGlobalFlowSpeed: 0.35,
      sgGlobalOpacity: 0.92,
    },
  },
  {
    id: 'rhythm-tribal-drums',
    title: 'Tribal Drums & Fuego Chamánico',
    description: 'Tambores chamánicos, polirritmias africanas y rituales de fuego. Texturas ocres y terracota con pulsos orgánicos telúricos.',
    category: 'rhythmic',
    author: { name: 'Ancestral Roots', handle: '@ancestral' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 19,
    folderPath: 'Librería/Presets Oficiales/Ritmos Musicales',
    createdAt: '2026-09-05T00:00:00Z',
    updatedAt: '2026-09-05T00:00:00Z',
    params: {
      k: 1.007,
      psi: 2.399,
      autoPilot: true,
      autoPilotMode: 'rhythmic',
      autoRandomMode: 'rhythmic',
      autoRandomOnBeat: true,
      autoRandomOnEmotionChange: true,
      autoEmotionSensitivity: 60,
      autoBeatSensitivity: 82,
      autoStyleFluidity: 62,
      autoRandomReactivitySpeed: 78,
      autoTransitionSmoothness: 70,
      autoRelationshipMode: 'rhythmic',
      autoViscosity: 0.955,
      autoSpeed: 1.15,
      baseHue: 18,
      hueRange: 60,
      saturation: 95,
      brightness: 12,
      harmonicColor: true,
      sacredGeometryEnabled: true,
      sacredGeometryModes: ['cymatics', 'merkaba', 'mandala1'],
      sgDrawMode: 'layers',
      sgShowNodes: true,
      sgAutoResonance: true,
      sgGlobalFlowSpeed: 0.34,
      sgGlobalOpacity: 0.9,
    },
  },
  {
    id: 'rhythm-jazz-fusion',
    title: 'Jazz Fusion & Bebop Club Nocturno',
    description: 'Azul cobalto y bronce ahumado. Sintonización empática con acordes extendidos, síncopas de platillos ride y solos virtuosos.',
    category: 'rhythmic',
    author: { name: 'Blue Note Explorer', handle: '@bluenote' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 20,
    folderPath: 'Librería/Presets Oficiales/Ritmos Musicales',
    createdAt: '2026-09-05T00:00:00Z',
    updatedAt: '2026-09-05T00:00:00Z',
    params: {
      k: 1.005,
      psi: 2.399,
      autoPilot: true,
      autoPilotMode: 'rhythmic',
      autoRandomMode: 'rainbow',
      autoRandomOnBeat: true,
      autoRandomOnEmotionChange: true,
      autoEmotionSensitivity: 75,
      autoBeatSensitivity: 65,
      autoStyleFluidity: 72,
      autoRandomReactivitySpeed: 68,
      autoTransitionSmoothness: 80,
      autoRelationshipMode: 'empathetic',
      autoViscosity: 0.965,
      autoSpeed: 0.95,
      baseHue: 215,
      hueRange: 240,
      saturation: 90,
      brightness: 11,
      harmonicColor: true,
      harmonicSensitivity: 6.8,
      sacredGeometryEnabled: true,
      sacredGeometryModes: ['vectorEquilibrium', 'cymatics', 'goldenSpiral'],
      sgDrawMode: 'layers',
      sgShowNodes: true,
      sgAutoResonance: true,
      sgGlobalFlowSpeed: 0.3,
      sgGlobalOpacity: 0.9,
    },
  },

  // =========================================================================
  // --- DERIVA & FLUIDEZ MEDITATIVA ---
  // =========================================================================
  {
    id: 'drift-eter-profundo',
    title: 'Éter Cósmico Hipnótico',
    description: 'Movimiento fluido ultra-sedoso con viscosidad alta (miel zen), ideal para meditación y música ambiental.',
    category: 'drift',
    author: { name: 'StarSeed Core', handle: '@starseed' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 21,
    folderPath: 'Librería/Presets Oficiales/Deriva & Fluidez',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
    params: {
      k: 1.002,
      psi: 2.399,
      autoPilot: true,
      autoPilotMode: 'drift',
      autoViscosity: 0.985,
      autoSpeed: 0.45,
      baseHue: 210,
      hueRange: 180,
      saturation: 85,
      brightness: 9,
      harmonicColor: true,
      harmonicSensitivity: 3.0,
      harmonicDepth: 180,
      autoRandomOnBeat: true,
    },
  },
  {
    id: 'drift-lofi-chill',
    title: 'Lo-Fi Chillhop Rainy Evening',
    description: 'Tonos sepia y lavanda suave. Fluidez melancólica y relajante perfecta para estudiar, programar o descansar con beats lofi.',
    category: 'drift',
    author: { name: 'LoFi Beats Sanctuary', handle: '@chillhop' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 22,
    folderPath: 'Librería/Presets Oficiales/Deriva & Fluidez',
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
    params: {
      k: 1.003,
      psi: 2.399,
      autoPilot: true,
      autoPilotMode: 'drift',
      autoRandomMode: 'drift',
      autoRandomOnBeat: true,
      autoRandomOnEmotionChange: true,
      autoEmotionSensitivity: 50,
      autoBeatSensitivity: 52,
      autoStyleFluidity: 65,
      autoViscosity: 0.978,
      autoSpeed: 0.55,
      autoRelationshipMode: 'empathetic',
      autoOffscreenFade: true,
      baseHue: 265,
      hueRange: 120,
      saturation: 75,
      brightness: 10,
      harmonicColor: true,
      sacredGeometryEnabled: true,
      sacredGeometryModes: ['torus', 'mandala1'],
      sgDrawMode: 'layers',
      sgShowNodes: true,
      sgAutoResonance: true,
      sgGlobalFlowSpeed: 0.22,
      sgGlobalOpacity: 0.85,
    },
  },
  {
    id: 'drift-catedral-ambient',
    title: 'Catedral Cósmica Ambient (Brian Eno)',
    description: 'Inmersión espacial infinita con nebulosas cian y azul profundo. Máxima viscosidad y respiración lenta para música ambiental y drones.',
    category: 'drift',
    author: { name: 'Ambient Soundscapes', handle: '@ambientscape' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 23,
    folderPath: 'Librería/Presets Oficiales/Deriva & Fluidez',
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
    params: {
      k: 1.001,
      psi: 2.399,
      autoPilot: true,
      autoPilotMode: 'drift',
      autoRandomMode: 'drift',
      autoRandomOnBeat: false,
      autoRandomOnEmotionChange: true,
      autoEmotionSensitivity: 70,
      autoBeatSensitivity: 35,
      autoStyleFluidity: 88,
      autoViscosity: 0.988,
      autoSpeed: 0.35,
      autoRelationshipMode: 'empathetic',
      autoOffscreenFade: true,
      baseHue: 190,
      hueRange: 140,
      saturation: 80,
      brightness: 9,
      harmonicColor: true,
      harmonicSensitivity: 7.2,
      sacredGeometryEnabled: true,
      sacredGeometryModes: ['metatron', 'quantumWave'],
      sgDrawMode: 'layers',
      sgShowNodes: true,
      sgAutoResonance: true,
      sgGlobalFlowSpeed: 0.18,
      sgGlobalOpacity: 0.88,
    },
  },

  // =========================================================================
  // --- CUÁNTICA & ALTA ENERGÍA ---
  // =========================================================================
  {
    id: 'quantum-aurora-boreal',
    title: 'Aurora Boreal Cuántica',
    description: 'Campos toroidales y ondas vibratorias de alta reactividad con colores esmeralda, cian y violeta fluorescente.',
    category: 'quantum',
    author: { name: 'StarSeed Labs', handle: '@starseed' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 24,
    folderPath: 'Librería/Presets Oficiales/Cuántica',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
    params: {
      k: 1.012,
      psi: 2.399,
      autoPilot: true,
      autoPilotMode: 'genesis',
      genesisStage: 5,
      autoViscosity: 0.94,
      autoSpeed: 1.4,
      baseHue: 170,
      hueRange: 360,
      saturation: 100,
      brightness: 14,
      harmonicColor: true,
      sacredGeometryEnabled: true,
      sacredGeometryModes: ['quantumWave', 'torus'],
      sgDrawMode: 'layers',
      sgShowNodes: true,
      sgAutoResonance: true,
      sgGlobalFlowSpeed: 0.4,
      sgGlobalOpacity: 0.9,
      autoRandomOnBeat: true,
    },
  },
  {
    id: 'portal-hiperdimensional',
    title: 'Portal AR Hiperdimensional (Alpha)',
    description: 'Túnel de perspectiva cuántica y difuminado de fuga con geometría fractal que proyecta un portal continuo al espacio.',
    category: 'quantum',
    author: { name: 'StarSeed Reality Lab', handle: '@realitylab' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 25,
    folderPath: 'Librería/Presets Oficiales/Cuántica',
    createdAt: '2026-09-03T00:00:00Z',
    updatedAt: '2026-09-03T00:00:00Z',
    params: {
      k: 1.008,
      psi: 2.399,
      autoPilot: true,
      autoPilotMode: 'genesis',
      autoViscosity: 0.95,
      autoSpeed: 1.1,
      baseHue: 195,
      hueRange: 300,
      saturation: 100,
      brightness: 12,
      arPortalMode: true,
      arPortalScale: 1.6,
      arPortalPerspectiveIntensity: 2.2,
      arPortalVanishingRadius: 1.5,
      arPortalFade: 1.1,
      arPortalBending: 0.25,
      sacredGeometryEnabled: true,
      sacredGeometryModes: ['torus', 'quantumWave'],
      sgAutoResonance: true,
      autoRandomOnBeat: true,
    },
  },
  {
    id: 'quantum-psytrance-goa',
    title: 'Psytrance Goa Mandala Hiperactivo',
    description: 'Mandala fractal hiperkinético para 145+ BPM. Mutaciones de color instantáneas en drops, neón verde ácido y púrpura ultra-reactivo.',
    category: 'quantum',
    author: { name: 'Goa Psy Collective', handle: '@goapsy' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 26,
    folderPath: 'Librería/Presets Oficiales/Cuántica',
    createdAt: '2026-09-04T00:00:00Z',
    updatedAt: '2026-09-04T00:00:00Z',
    params: {
      k: 1.014,
      psi: 1.57,
      autoPilot: true,
      autoPilotMode: 'astral',
      autoRandomMode: 'astral',
      autoRandomOnBeat: true,
      autoRandomOnEmotionChange: true,
      autoEmotionSensitivity: 70,
      autoBeatSensitivity: 88,
      autoStyleFluidity: 90,
      autoRandomReactivitySpeed: 88,
      autoTransitionSmoothness: 75,
      autoRelationshipMode: 'technical',
      autoViscosity: 0.93,
      autoSpeed: 1.45,
      baseHue: 110,
      hueRange: 360,
      saturation: 100,
      brightness: 15,
      harmonicColor: true,
      sacredGeometryEnabled: true,
      sacredGeometryModes: ['metatron', 'holographicFractal', 'quantumWave'],
      sgDrawMode: 'layers',
      sgShowNodes: true,
      sgAutoResonance: true,
      sgGlobalFlowSpeed: 0.5,
      sgGlobalOpacity: 0.96,
    },
  },
  {
    id: 'quantum-dubstep-cannon',
    title: 'Dubstep Bass Cannon & Sub Drop',
    description: 'Estallido explosivo para subgraves pesados y wobble bass. Toroides cuánticos reactivos a frecuencias sub-bajas y transitorios masivos.',
    category: 'quantum',
    author: { name: 'Subwoofer Dynamics', handle: '@subwoofer' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 27,
    folderPath: 'Librería/Presets Oficiales/Cuántica',
    createdAt: '2026-09-05T00:00:00Z',
    updatedAt: '2026-09-05T00:00:00Z',
    params: {
      k: 1.015,
      psi: 3.14,
      autoPilot: true,
      autoPilotMode: 'dj',
      autoRandomMode: 'dj',
      autoRandomOnBeat: true,
      autoRandomOnEmotionChange: true,
      autoEmotionSensitivity: 65,
      autoBeatSensitivity: 92,
      autoStyleFluidity: 75,
      autoRandomReactivitySpeed: 92,
      autoTransitionSmoothness: 82,
      autoRelationshipMode: 'technical',
      autoViscosity: 0.935,
      autoSpeed: 1.4,
      baseHue: 85,
      hueRange: 360,
      saturation: 100,
      brightness: 15,
      harmonicColor: true,
      sacredGeometryEnabled: true,
      sacredGeometryModes: ['torus', 'quantumWave', 'vectorEquilibrium'],
      sgDrawMode: 'layers',
      sgShowNodes: true,
      sgAutoResonance: true,
      sgGlobalFlowSpeed: 0.48,
      sgGlobalOpacity: 0.95,
    },
  },

  // =========================================================================
  // --- COMUNIDAD STARSEED ---
  // =========================================================================
  {
    id: 'community-pulsar-astral',
    title: 'Púlsar Astral de la Red',
    description: 'Preset colectivo de resonancia fractal con contrastes dorados y tornasol aportado por la comunidad.',
    category: 'community',
    author: { name: 'Comunidad StarSeed', handle: '@comunidad' },
    isOfficial: false,
    isPublic: true,
    orderIndex: 28,
    folderPath: 'Librería/Librería Pública StarSeed/Comunidad',
    createdAt: '2026-09-05T12:00:00Z',
    updatedAt: '2026-09-05T12:00:00Z',
    params: {
      k: 1.009,
      psi: 2.399,
      autoPilot: true,
      autoPilotMode: 'drift',
      autoRandomMode: 'rhythmic',
      autoRandomOnBeat: true,
      autoViscosity: 0.95,
      autoSpeed: 1.1,
      baseHue: 35,
      hueRange: 320,
      saturation: 100,
      brightness: 12,
      harmonicColor: true,
    },
  },
];

