import { AudiomorphicPresetRecord } from './starseedDb';

export const DEFAULT_PRESETS: AudiomorphicPresetRecord[] = [
  // --- GÉNESIS SAGRADO ---
  {
    id: 'genesis-metatron-supremo',
    title: 'Cubo de Metatrón Supremo',
    description: 'Geometría sagrada en máxima complejidad (V:13, E:78) con capas resonantes infinitas y respiración armónica expansiva.',
    category: 'genesis',
    author: { name: 'StarSeed Core', handle: '@starseed' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 0,
    folderPath: 'Biblioteca/Presets Oficiales/Génesis Sagrado',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
    params: {
      k: 1.006,
      psi: 2.399,
      autoPilot: true,
      autoPilotMode: 'genesis',
      genesisStage: 6,
      autoViscosity: 0.965,
      autoSpeed: 1.0,
      baseHue: 45,
      hueRange: 360,
      saturation: 100,
      brightness: 12,
      harmonicColor: true,
      sgResonanceModes: ['goldenSpiral', 'flowerOfLife', 'quantumWave', 'torus'],
      sgDrawMode: 'layers',
      sgShowNodes: true,
      sgAutoResonance: true,
    },
  },
  {
    id: 'genesis-flor-vida',
    title: 'Flor de la Vida Luminosa',
    description: 'Resonancia pura de 19 vértices y 36 aristas en régimen primario de balance yin-yang.',
    category: 'genesis',
    author: { name: 'StarSeed Core', handle: '@starseed' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 1,
    folderPath: 'Biblioteca/Presets Oficiales/Génesis Sagrado',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
    params: {
      k: 1.004,
      psi: 2.399,
      autoPilot: true,
      autoPilotMode: 'genesis',
      genesisStage: 4,
      autoViscosity: 0.97,
      autoSpeed: 0.8,
      baseHue: 155,
      hueRange: 300,
      saturation: 95,
      brightness: 12,
      harmonicColor: true,
      sgResonanceModes: ['flowerOfLife'],
      sgDrawMode: 'layers',
      sgShowNodes: true,
      sgAutoResonance: true,
    },
  },

  // --- ARMÓNICOS & FRECUENCIAS ---
  {
    id: 'harmonic-solfeggio-528',
    title: 'Frecuencia de Transformación 528Hz',
    description: 'Afinación áurea y transiciones armónicas continuas que siguen las progresiones sonoras.',
    category: 'harmonic',
    author: { name: 'Omnifrecuencias Labs', handle: '@omnifrecuencias' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 2,
    folderPath: 'Biblioteca/Presets Oficiales/Armónicos',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
    params: {
      k: 1.008,
      psi: 2.399,
      autoPilot: true,
      autoPilotMode: 'harmonic',
      rootNote: 0,
      autoViscosity: 0.96,
      autoSpeed: 1.2,
      baseHue: 120,
      hueRange: 360,
      saturation: 100,
      brightness: 11,
      harmonicColor: true,
      harmonicSensitivity: 6.5,
      harmonicDepth: 360,
    },
  },
  {
    id: 'harmonic-circulo-quintas',
    title: 'Círculo Cósmico de Quintas',
    description: 'Mapeo modal de tonalidades cromáticas con rotación angular según el espectro del sonido.',
    category: 'harmonic',
    author: { name: 'StarSeed Core', handle: '@starseed' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 3,
    folderPath: 'Biblioteca/Presets Oficiales/Armónicos',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
    params: {
      k: 1.005,
      psi: 1.618,
      autoPilot: true,
      autoPilotMode: 'harmonic',
      rootNote: 7,
      autoViscosity: 0.955,
      autoSpeed: 1.0,
      baseHue: 280,
      hueRange: 360,
      saturation: 100,
      brightness: 10,
      harmonicColor: true,
      harmonicSensitivity: 5.0,
      harmonicDepth: 360,
    },
  },

  // --- DERIVA MEDITATIVA ---
  {
    id: 'drift-eter-profundo',
    title: 'Éter Cósmico Hipnótico',
    description: 'Movimiento fluido ultra-sedoso con viscosidad alta (miel zen), ideal para meditación y música ambiental.',
    category: 'drift',
    author: { name: 'StarSeed Core', handle: '@starseed' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 4,
    folderPath: 'Biblioteca/Presets Oficiales/Meditación',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
    params: {
      k: 1.002,
      psi: 2.399,
      autoPilot: true,
      autoPilotMode: 'drift',
      autoViscosity: 0.985,
      autoSpeed: 0.45,
      baseHue: 210,
      hueRange: 180,
      saturation: 85,
      brightness: 9,
      harmonicColor: true,
      harmonicSensitivity: 3.0,
      harmonicDepth: 180,
    },
  },

  // --- CUÁNTICA & ALTA ENERGÍA ---
  {
    id: 'quantum-aurora-boreal',
    title: 'Aurora Boreal Cuántica',
    description: 'Campos toroidales y ondas vibratorias de alta reactividad con colores esmeralda, cian y violeta fluorescente.',
    category: 'quantum',
    author: { name: 'StarSeed Labs', handle: '@starseed' },
    isOfficial: true,
    isPublic: true,
    orderIndex: 5,
    folderPath: 'Biblioteca/Presets Oficiales/Cuántica',
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
    params: {
      k: 1.012,
      psi: 2.399,
      autoPilot: true,
      autoPilotMode: 'genesis',
      genesisStage: 5,
      autoViscosity: 0.94,
      autoSpeed: 1.4,
      baseHue: 170,
      hueRange: 360,
      saturation: 100,
      brightness: 14,
      harmonicColor: true,
      sgResonanceModes: ['quantumWave', 'torus'],
      sgDrawMode: 'layers',
      sgShowNodes: true,
      sgAutoResonance: true,
    },
  },

  // --- COMUNIDAD STARSEED ---
  {
    id: 'community-pulsar-astral',
    title: 'Púlsar Astral de la Red',
    description: 'Preset colectivo de resonancia fractal con contrastes dorados y tornasol aportado por la comunidad.',
    category: 'community',
    author: { name: 'Comunidad StarSeed', handle: '@comunidad' },
    isOfficial: false,
    isPublic: true,
    orderIndex: 6,
    folderPath: 'Biblioteca/Librería Pública StarSeed/Comunidad',
    createdAt: '2026-09-05T12:00:00Z',
    updatedAt: '2026-09-05T12:00:00Z',
    params: {
      k: 1.009,
      psi: 2.399,
      autoPilot: true,
      autoPilotMode: 'drift',
      autoViscosity: 0.95,
      autoSpeed: 1.1,
      baseHue: 35,
      hueRange: 320,
      saturation: 100,
      brightness: 12,
      harmonicColor: true,
    },
  },
];
